__module_name__ = "matixgen.py"
__module_version__ = "2.0"
__module_description__ = "MATIX HAS U"

import xchat, random, string, time
xchat.prnt(">> " + __module_name__ + " " + __module_version__ + " loaded.")

def color(solid=False):
    color_range = range(2, 16)
    if solid:
        fg = bg = random.choice(color_range)
    else:
        fg = random.choice(color_range)
        color_range.remove(fg)
        bg = random.choice(color_range)
    return '%s,%s' % (fg, bg)

def matixgen(word, word_eol, userdata):
    try:
        speed = int(word[1])
        letters = word_eol[2].upper()
        check = [i for i in letters if i not in string.letters]
        if check:
            xchat.prnt("[!] matxigen.py Error: Only letters allowed!")
            return xchat.EAT_ALL
    except:
        xchat.prnt("[!] matixgen.py Error: Invalid arguments!")
    else:
        border_char = 'h'
        text = []
        placeholder = ''
        border_one = ''+border_char+''
        border_two = border_char+''
        for x in range(16):
            color_one = color()
            color_two = color()
            placeholder += color_one+border_one
            placeholder += color_two+border_two
        first_line = placeholder+color_one+border_one+color_two+border_two
        xchat.command("say "+first_line)
        inner_fg = color(solid=True)+border_char
        inner_bg = color(solid=True)
        border_color = '1,1'
        for letter in letters:
            big_letter = big_letters.get(letter)
            for i in big_letter:
                line = color()+border_one+i.replace(':', inner_fg)
                line = line.replace(letter, border_color+letter+'')
                line = line.replace(' ', inner_bg+border_char+'')
                line = line+color()+border_two 
                text.append(line)
        text.append(first_line)
        ctx = xchat.get_context()
        def on_timer(userdata):
            for txt in text:
                ctx.command("say %s" % txt.rstrip('\n'))
                return text.pop(0)
        xchat.hook_timer(speed, on_timer)
    return xchat.EAT_ALL
xchat.hook_command("mg", matixgen, help="/mg [speed] [letters]")

big_letters = {

    "A":["                AA                ",
    "               A::A               ",
    "              A::::A              ",
    "             A::::::A             ",
    "            A::::::::A            ",
    "           A::::A:::::A           ",
    "          A:::::AA:::::A          ",
    "         A:::::A  A:::::A         ",
    "        A:::::A    A:::::A        ",
    "       A:::::AAAAAAAA:::::A       ",
    "      A::::::::::::::::::::A      ",
    "     A:::::AAAAAAAAAAAA:::::A     ",
    "    A:::::A            A:::::A    ",
    "   A:::::A              A:::::A   ",
    "  A:::::A                A:::::A  ",
    " AAAAAA                    AAAAAA ",
    ]
    ,
    "B":[
    "        BBBBBBBBBBBBBBBBB         ",
    "        B::::::::::::::::B        ",
    "        B::::::BBBBBB:::::B       ",
    "        BB:::::B     B:::::B      ",
    "          B::::B     B:::::B      ",
    "          B::::B     B:::::B      ",
    "          B::::BBBBBB:::::B       ",
    "          B:::::::::::::BB        ",
    "          B::::BBBBBB:::::B       ",
    "          B::::B     B:::::B      ",
    "          B::::B     B:::::B      ",
    "          B::::B     B:::::B      ",
    "        BB:::::BBBBBB::::::B      ",
    "        B:::::::::::::::::B       ",
    "        B::::::::::::::::B        ",
    "        BBBBBBBBBBBBBBBBB         ",
    ],
    "C":[
    "              CCCCCCCCCCCCC       ",
    "           CCC::::::::::::C       ",
    "         CC:::::::::::::::C       ",
    "        C:::::CCCCCCCC::::C       ",
    "       C:::::C       CCCCCC       ",
    "      C:::::C                     ",
    "      C:::::C                     ",
    "      C:::::C                     ",
    "      C:::::C                     ",
    "      C:::::C                     ",
    "      C:::::C                     ",
    "       C:::::C       CCCCCC       ",
    "        C:::::CCCCCCCC::::C       ",
    "         CC:::::::::::::::C       ",
    "           CCC::::::::::::C       ",
    "              CCCCCCCCCCCCC       ",
    ],
    "D":["      DDDDDDDDDDDDD               ",
    "      D::::::::::::DDD            ",
    "      D:::::::::::::::DD          ",
    "      DDD:::::DDDDD:::::D         ",
    "        D:::::D    D:::::D        ",
    "        D:::::D     D:::::D       ",
    "        D:::::D     D:::::D       ",
    "        D:::::D     D:::::D       ",
    "        D:::::D     D:::::D       ",
    "        D:::::D     D:::::D       ",
    "        D:::::D     D:::::D       ",
    "        D:::::D    D:::::D        ",
    "      DDD:::::DDDDD:::::D         ",
    "      D:::::::::::::::DD          ",
    "      D::::::::::::DDD            ",
    "      DDDDDDDDDDDDD               ",
    ],
    "E":["     EEEEEEEEEEEEEEEEEEEEEE       ",
    "     E::::::::::::::::::::E       ",
    "     E::::::::::::::::::::E       ",
    "     EE::::::EEEEEEEEE::::E       ",
    "       E:::::E       EEEEEE       ",
    "       E:::::E                    ",
    "       E::::::EEEEEEEEEE          ",
    "       E:::::::::::::::E          ",
    "       E:::::::::::::::E          ",
    "       E::::::EEEEEEEEEE          ",
    "       E:::::E                    ",
    "       E:::::E       EEEEEE       ",
    "     EE::::::EEEEEEEE:::::E       ",
    "     E::::::::::::::::::::E       ",
    "     E::::::::::::::::::::E       ",
    "     EEEEEEEEEEEEEEEEEEEEEE       ",
    ],
    "F":[
    "      FFFFFFFFFFFFFFFFFFFFFF      ",
    "      F::::::::::::::::::::F      ",
    "      F::::::::::::::::::::F      ",
    "      FF::::::FFFFFFFFF::::F      ",
    "        F:::::F       FFFFFF      ",
    "        F:::::F                   ",
    "        F::::::FFFFFFFFFF         ",
    "        F:::::::::::::::F         ",
    "        F:::::::::::::::F         ",
    "        F::::::FFFFFFFFFF         ",
    "        F:::::F                   ",
    "        F:::::F                   ",
    "      FF:::::::FF                 ",
    "      F::::::::FF                 ",
    "      F::::::::FF                 ",
    "      FFFFFFFFFFF                 ",
    ],
    "G":[
    "              GGGGGGGGGGGGG       ",
    "           GGG::::::::::::G       ",
    "         GG:::::::::::::::G       ",
    "        G:::::GGGGGGGG::::G       ",
    "       G:::::G       GGGGGG       ",
    "      G:::::G                     ",
    "      G:::::G                     ",
    "      G:::::G    GGGGGGGGGG       ",
    "      G:::::G    G::::::::G       ",
    "      G:::::G    GGGGG::::G       ",
    "      G:::::G        G::::G       ",
    "       G:::::G       G::::G       ",
    "        G:::::GGGGGGGG::::G       ",
    "         GG:::::::::::::::G       ",
    "           GGG:::::::::::GG       ",
    "             GGGGGGGGGGGGG        ",
    ],
    "H":["     HHHHHHHHH     HHHHHHHHH      ",
    "     H:::::::H     H:::::::H      ",
    "     H:::::::H     H:::::::H      ",
    "     HH::::::H     H::::::HH      ",
    "       H:::::H     H:::::H        ",
    "       H:::::H     H:::::H        ",
    "       H::::::HHHHH::::::H        ",
    "       H:::::::::::::::::H        ",
    "       H:::::::::::::::::H        ",
    "       H::::::HHHHH::::::H        ",
    "       H:::::H     H:::::H        ",
    "       H:::::H     H:::::H        ",
    "     HH::::::H     H::::::HH      ",
    "     H:::::::H     H:::::::H      ",
    "     H:::::::H     H:::::::H      ",
    "     HHHHHHHHH     HHHHHHHHH      ",
    ],
    "I":["            IIIIIIIIII            ",
    "            I::::::::I            ",
    "            I::::::::I            ",
    "            II::::::II            ",
    "              I::::I              ",
    "              I::::I              ",
    "              I::::I              ",
    "              I::::I              ",
    "              I::::I              ",
    "              I::::I              ",
    "              I::::I              ",
    "              I::::I              ",
    "            II::::::II            ",
    "            I::::::::I            ",
    "            I::::::::I            ",
    "            IIIIIIIIII            ",
    ],
    "J":["             JJJJJJJJJJJ          ",
    "             J:::::::::J          ",
    "             J:::::::::J          ",
    "             JJ:::::::JJ          ",
    "               J:::::J            ",
    "               J:::::J            ",
    "               J:::::J            ",
    "               J:::::J            ",
    "               J:::::J            ",
    "   JJJJJJJ     J:::::J            ",
    "   J:::::J     J:::::J            ",
    "   J::::::J   J::::::J            ",
    "   J:::::::JJJ:::::::J            ",
    "    JJ:::::::::::::JJ             ",
    "      JJ:::::::::JJ               ",
    "        JJJJJJJJJ                 ",
    ],
    "K":["      KKKKKKKKK    KKKKKKKK       ",
    "      K:::::::K    K::::::K       ",
    "      K:::::::K    K::::::K       ",
    "      K:::::::K   K:::::::K       ",
    "      KK::::::K  K:::::KKK        ",
    "        K:::::K K:::::K           ",
    "        K::::::K:::::K            ",
    "        K:::::::::::K             ",
    "        K:::::::::::K             ",
    "        K::::::K:::::K            ",
    "        K:::::K K:::::K           ",
    "      KK::::::K  K:::::KKK        ",
    "      K:::::::K   K:::::::K       ",
    "      K:::::::K    K::::::K       ",
    "      K:::::::K    K::::::K       ",
    "      KKKKKKKKK    KKKKKKKK       ",
    ],
    "L":["            LLLLLLLLL             ",
    "           L:::::::::L            ",
    "           L:::::::::L            ",
    "           LL:::::::LL            ",
    "             L:::::L              ",
    "             L:::::L              ",
    "             L:::::L              ",
    "             L:::::L              ",
    "             L:::::L              ",
    "             L:::::L              ",
    "             L:::::L              ",
    "             L:::::L   LLLLLL     ",
    "           LL::::::LLLL:::::L     ",
    "           L::::::::::::::::L     ",
    "           L::::::::::::::::L     ",
    "           LLLLLLLLLLLLLLLLLL     ",
    ],
    "M":[" MMMMMMMM               MMMMMMMM  ",
    " M:::::::M             M:::::::M  ",
    " M::::::::M           M::::::::M  ",
    " M:::::::::M         M:::::::::M  ",
    " M::::::::::M       M::::::::::M  ",
    " M:::::::::::M     M:::::::::::M  ",
    " M:::::::M::::M   M::::M:::::::M  ",
    " M::::::M M::::M M::::M M::::::M  ",
    " M::::::M  M::::M::::M  M::::::M  ",
    " M::::::M   M:::::::M   M::::::M  ",
    " M::::::M    M:::::M    M::::::M  ",
    " M::::::M     MMMMM     M::::::M  ",
    " M::::::M               M::::::M  ",
    " M::::::M               M::::::M  ",
    " M::::::M               M::::::M  ",
    " MMMMMMMM               MMMMMMMM  ",
    ],
    "N":["    NNNNNNNN        NNNNNNNN      ",
    "    N:::::::N       N::::::N      ",
    "    N::::::::N      N::::::N      ",
    "    N:::::::::N     N::::::N      ",
    "    N::::::::::N    N::::::N      ",
    "    N:::::::::::N   N::::::N      ",
    "    N:::::::N::::N  N::::::N      ",
    "    N::::::N N::::N N::::::N      ",
    "    N::::::N  N::::N:::::::N      ",
    "    N::::::N   N:::::::::::N      ",
    "    N::::::N    N::::::::::N      ",
    "    N::::::N     N:::::::::N      ",
    "    N::::::N      N::::::::N      ",
    "    N::::::N       N:::::::N      ",
    "    N::::::N        N::::::N      ",
    "    NNNNNNNN         NNNNNNN      ",
    ],
    "O":["            OOOOOOOOO             ",
    "          OO:::::::::OO           ",
    "        OO:::::::::::::OO         ",
    "       O:::::::OOO:::::::O        ",
    "       O::::::O   O::::::O        ",
    "       O:::::O     O:::::O        ",
    "       O:::::O     O:::::O        ",
    "       O:::::O     O:::::O        ",
    "       O:::::O     O:::::O        ",
    "       O:::::O     O:::::O        ",
    "       O:::::O     O:::::O        ",
    "       O::::::O   O::::::O        ",
    "       O:::::::OOO:::::::O        ",
    "        OO:::::::::::::OO         ",
    "          OO:::::::::OO           ",
    "            OOOOOOOOO             ",
    ],
    "P":["        PPPPPPPPPPPPPPPPP         ",
    "       P::::::::::::::::P         ",
    "       P::::::PPPPPP:::::P        ",
    "       PP:::::P     P:::::P       ",
    "         P::::P     P:::::P       ",
    "         P::::P     P:::::P       ",
    "         P::::PPPPPP:::::P        ",
    "         P:::::::::::::PP         ",
    "         P::::PPPPPPPPP           ",
    "         P::::P                   ",
    "         P::::P                   ",
    "         P::::P                   ",
    "       PP::::::PP                 ",
    "       P::::::::P                 ",
    "       P::::::::P                 ",
    "       PPPPPPPPPP                 ",
    ],
    "Q":["           QQQQQQQQQ              ",
    "          QQ:::::::::QQ           ",
    "        QQ:::::::::::::QQ         ",
    "       Q:::::::QQQ:::::::Q        ",
    "       Q::::::Q   Q::::::Q        ",
    "       Q:::::Q     Q:::::Q        ",
    "       Q:::::Q     Q:::::Q        ",
    "       Q:::::Q     Q:::::Q        ",
    "       Q:::::Q     Q:::::Q        ",
    "       Q:::::Q     Q:::::Q        ",
    "       Q:::::Q  QQQQ:::::Q        ",
    "       Q::::::Q Q::::::::Q        ",
    "       Q:::::::QQ::::::::Q        ",
    "        QQ::::::::::::::Q         ",
    "          QQ:::::::::::Q          ",
    "            QQQQQQQQ::::QQ        ",
    "                   Q:::::Q        ",
    "                     QQQQQQ       ",
    ],
    "R":["      RRRRRRRRRRRRRRRRR           ",
    "      R::::::::::::::::R          ",
    "      R::::::RRRRRR:::::R         ",
    "      RR:::::R     R:::::R        ",
    "        R::::R     R:::::R        ",
    "        R::::R     R:::::R        ",
    "        R::::RRRRRR:::::R         ",
    "        R:::::::::::::RR          ",
    "        R::::RRRRRR:::::R         ",
    "        R::::R     R:::::R        ",
    "        R::::R     R:::::R        ",
    "        R::::R     R:::::R        ",
    "      RR:::::R     R:::::R        ",
    "      R::::::R     R:::::R        ",
    "      R::::::R     R:::::R        ",
    "      RRRRRRRR     RRRRRRR        ",
    ],
    "S":["          SSSSSSSSSSSSSSS         ",
    "        SS:::::::::::::::S        ",
    "       S:::::SSSSSS::::::S        ",
    "       S:::::S     SSSSSSS        ",
    "       S:::::S                    ",
    "       S:::::S                    ",
    "        S::::SSSS                 ",
    "         SS::::::SSSSS            ",
    "           SSS::::::::SS          ",
    "              SSSSSS::::S         ",
    "                   S:::::S        ",
    "                   S:::::S        ",
    "       SSSSSSS     S:::::S        ",
    "       S::::::SSSSSS:::::S        ",
    "       S:::::::::::::::SS         ",
    "        SSSSSSSSSSSSSSS           ",
    ],
    "T":["     TTTTTTTTTTTTTTTTTTTTTTT      ",
    "     T:::::::::::::::::::::T      ",
    "     T:::::::::::::::::::::T      ",
    "     T:::::TT:::::::TT:::::T      ",
    "     TTTTTT  T:::::T  TTTTTT      ",
    "             T:::::T              ",
    "             T:::::T              ",
    "             T:::::T              ",
    "             T:::::T              ",
    "             T:::::T              ",
    "             T:::::T              ",
    "             T:::::T              ",
    "           TT:::::::TT            ",
    "           T:::::::::T            ",
    "           T:::::::::T            ",
    "           TTTTTTTTTTT            ",
    ],
    "U":["      UUUUUUUU     UUUUUUUU       ",
    "      U::::::U     U::::::U       ",
    "      U::::::U     U::::::U       ",
    "      UU:::::U     U:::::UU       ",
    "       U:::::U     U:::::U        ",
    "       U:::::U     U:::::U        ",
    "       U:::::U     U:::::U        ",
    "       U:::::U     U:::::U        ",
    "       U:::::U     U:::::U        ",
    "       U:::::U     U:::::U        ",
    "       U:::::U     U:::::U        ",
    "       U::::::U   U::::::U        ",
    "       U:::::::UUU:::::::U        ",
    "        UU:::::::::::::UU         ",
    "          UU:::::::::UU           ",
    "            UUUUUUUUU             ",
    ],
    "V":[
    "   VVVVVVVV           VVVVVVVV    ",
    "   V::::::V           V::::::V    ",
    "   V::::::V           V::::::V    ",
    "   V::::::V           V::::::V    ",
    "    V:::::V           V:::::V     ",
    "     V:::::V         V:::::V      ",
    "      V:::::V       V:::::V       ",
    "       V:::::V     V:::::V        ",
    "        V:::::V   V:::::V         ",
    "         V:::::V V:::::V          ",
    "          V:::::V:::::V           ",
    "           V:::::::::V            ",
    "            V:::::::V             ",
    "             V:::::V              ",
    "              V:::V               ",
    "               VVV                ",
    ],
    "W":["WWWWWWWW                 WWWWWWWW ",
    "W::::W                     W::::W ",
    "W::::W                     W::::W ",
    "W::::W                     W::::W ",
    " W:::W        WWWW         W:::W  ",
    "  W:::W       W:::W       W:::W   ",
    "   W:::W     W:::::W     W:::W    ",
    "    W:::W   W:::::::W   W:::W     ",
    "    W:::W  W::::W::::W  W:::W     ",
    "     W:::W W:::W W:::W W:::W      ",
    "      W:::W:::W   W:::W:::W       ",
    "        W::::::W  W::::::W        ",
    "         W:::::W  W:::::W         ",
    "          W:::W   W:::W           ",
    "          W::W     W::W           ",
    "          WWW       WWW           ",
    ],
    "X":["      XXXXXXX       XXXXXXX       ",
    "      X:::::X       X:::::X       ",
    "      X:::::X       X:::::X       ",
    "      X::::::X     X::::::X       ",
    "      XXX:::::X   X:::::XXX       ",
    "         X:::::X X:::::X          ",
    "          X:::::X:::::X           ",
    "           X:::::::::X            ",
    "           X:::::::::X            ",
    "          X:::::X:::::X           ",
    "         X:::::X X:::::X          ",
    "      XXX:::::X   X:::::XXX       ",
    "      X::::::X     X::::::X       ",
    "      X:::::X       X:::::X       ",
    "      X:::::X       X:::::X       ",
    "      XXXXXXX       XXXXXXX       ",
    ],
    "Y":["      YYYYYYY       YYYYYYY       ",
    "      Y:::::Y       Y:::::Y       ",
    "      Y:::::Y       Y:::::Y       ",
    "      Y::::::Y     Y::::::Y       ",
    "      YYY:::::Y   Y:::::YYY       ",
    "         Y:::::Y Y:::::Y          ",
    "          Y:::::Y:::::Y           ",
    "           Y:::::::::Y            ",
    "            Y:::::::Y             ",
    "             Y:::::Y              ",
    "             Y:::::Y              ",
    "             Y:::::Y              ",
    "             Y:::::Y              ",
    "          YYYY:::::YYYY           ",
    "          Y:::::::::::Y           ",
    "          YYYYYYYYYYYYY           ",
    ],
    "Z":["       ZZZZZZZZZZZZZZZZZZZ        ",
    "       Z:::::::::::::::::Z        ",
    "       Z:::::::::::::::::Z        ",
    "       Z:::ZZZZZZZZ:::::Z         ",
    "       ZZZZZ     Z:::::Z          ",
    "               Z:::::Z            ",
    "              Z:::::Z             ",
    "             Z:::::Z              ",
    "            Z:::::Z               ",
    "           Z:::::Z                ",
    "          Z:::::Z                 ",
    "       ZZZ:::::Z     ZZZZZ        ",
    "       Z::::::ZZZZZZZZ:::Z        ",
    "       Z:::::::::::::::::Z        ",
    "       Z:::::::::::::::::Z        ",
    "       ZZZZZZZZZZZZZZZZZZZ        ",
    ]
}

